### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by dev-forty-two** [dawsers/scroll#116]
### Please fill out the following:
- **Scroll Version:**
1.12-dev-e00ca868

- **Debug Log:**
https://0x0.st/K2eC.txt

- **Stack Trace:**
```
(gdb) bt full
#0  layout_toggle_size_get_container (workspace=0x0) at ../sway-scroll-git/sway/tree/layout.c:3564
#1  layout_toggle_size_change_focus (last_focus=<optimized out>, new_focus=0x56462b9af410) at ../sway-scroll-git/sway/tree/layout.c:3980
        old_active = <optimized out>
        new_workspace = 0x0
        new_container = 0x56462b9af410
        last_workspace = <optimized out>
        last_container = <optimized out>
#2  seat_set_workspace_focus (seat=<optimized out>, node=0x56462b9af410) at ../sway-scroll-git/sway/input/seat.c:1280
        last_focus = <optimized out>
        last_workspace = 0x56462b1fe730
        new_workspace = <optimized out>
        container = <optimized out>
        new_output = <optimized out>
        new_output_last_ws = <optimized out>
#3  0x000056460c4b0382 in seat_set_focus (seat=seat@entry=0x56462b1e0950, node=0x56462b9af410) at ../sway-scroll-git/sway/input/seat.c:1292
#4  0x000056460c4b6e0c in handle_button (seat=0x56462b1e0950, time_msec=1229259, device=<optimized out>, button=272, state=WL_POINTER_BUTTON_STATE_PRESSED)
    at ../sway-scroll-git/sway/input/seatop_default.c:453
        cursor = 0x56462a5a17d0
        surface = 0x56462b9c26e0
        sx = 1084.4786484247643
        sy = 108.22867982990729
        node = <optimized out>
        cont = <optimized out>
        is_floating = <optimized out>
        is_floating_or_child = <optimized out>
        is_fullscreen_or_child = <optimized out>
        edge = <optimized out>
        resize_edge = <optimized out>
        on_border = <optimized out>
        on_contents = <optimized out>
        on_workspace = <optimized out>
        on_titlebar = <optimized out>
        keyboard = <optimized out>
        modifiers = <optimized out>
        mod_pressed = <optimized out>
        mod_move_btn = <optimized out>
        mod_resize_btn = <optimized out>
        mod_move_btn_pressed = <optimized out>
        mod_resize_btn_pressed = <optimized out>
        titlebar_left_btn_pressed = <optimized out>
        mod_scroll_btn_pressed = <optimized out>
        layer = <optimized out>
        xsurface = <optimized out>
#5  0x00007fcc2ac9b4d0 in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
#6  0x00007fcc2ac9b4d0 in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
#7  0x00007fcc2abac757 in handle_pointer_button (event=0x56462bace270, pointer=0x56462b65ecf8) at ../wlroots-git/backend/libinput/pointer.c:72
--Type <RET> for more, q to quit, c to continue without paging--
        pevent = 0x56462bace270
        wlr_event = {pointer = 0x56462b65ecf8, time_msec = 1229259, button = 272, state = WL_POINTER_BUTTON_STATE_PRESSED}
#8  handle_libinput_event (backend=<optimized out>, event=0x56462bace270) at ../wlroots-git/backend/libinput/events.c:167
        libinput_dev = <optimized out>
        dev = 0x56462b65eb70
        event_type = <optimized out>
#9  handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=<optimized out>) at ../wlroots-git/backend/libinput/backend.c:59
        backend = <optimized out>
        ret = <optimized out>
        event = 0x56462bace270
#10 handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=<optimized out>) at ../wlroots-git/backend/libinput/backend.c:49
        backend = <optimized out>
        ret = <optimized out>
        event = <optimized out>
#11 0x00007fcc2ac9d182 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#12 0x00007fcc2ac9f297 in wl_display_run () at /usr/lib/libwayland-server.so.0
#13 0x000056460c485c13 in server_run (server=<optimized out>) at ../sway-scroll-git/sway/server.c:616
#14 main (argc=<optimized out>, argv=<optimized out>) at ../sway-scroll-git/sway/main.c:376
        config_path = 0x0
        c = <optimized out>
        validate = false
        debug = false
        verbose = false
```
- **Description:**
  I autostart `thunderbird` as a floating window in scratchpad. `scroll` crashes consistently when I bring the thunderbird window to the front, reload `scroll`, and click on an email in thunderbird!

**Comment by dawsers** [comment]
The bt is very useful, and it is clear where the problem is. But to fix it, I need to see how it affects the logic, so please, bear with me...

When you say `reload scroll`, so you mean reload the configuration (as in `$mod+shift+c`), or something else? This is what I have tried, please correct my procedure or even better, post your exact window rule and procedure.

In my config
```
    for_window [app_id="thunderbird" title="Mozilla Thunderbird"] move scratchpad
    exec thunderbird
```

Now I start scroll, and hit `$mod+z` to bring up the scratchpad (and thunderbird in it).

If I reload the configuration now, it will make Thunderbird leave the scratchpad and simply become a floating window in the current workspace.

If I don't reload the configuration and click on a mail, it seems to be working.

So I must be doing something differently than you are.

Thanks.

**Comment by dev-forty-two** [comment]
> When you say `reload scroll`, so you mean reload the configuration (as in `$mod+shift+c`), or something else? This is what I have tried, please correct my procedure or even better, post your exact window rule and procedure.

Yes, I reload the config via `$mod+shift+c`.

These are my thunderbird window rules (the last two deal with compose windows and are probably not relevant here):

```
bindsym $mod+Ctrl+e [app_id="thunderbird"] scratchpad show; move position center; resize set 98 ppt 98 ppt
for_window [app_id="thunderbird"] floating enable
for_window [title="^.*Mozilla Thunderbird$" app_id="thunderbird"] resize set 98 ppt 93 ppt
for_window [title="^.*Mozilla Thunderbird$" app_id="thunderbird"] move position center
for_window [title="^.*Mozilla Thunderbird$" app_id="thunderbird"] move scratchpad
for_window [title="^Write.*Thunderbird$" app_id="thunderbird"] resize set 80 ppt 85 ppt
for_window [title="^Write.*Thunderbird$" app_id="thunderbird"] move position center
```

Here's the full procedure: I start scroll, thunderbird is autostarted (`exec sleep 5s && thunderbird`), I press `$mod+Ctrl+e`, thunderbird pops up, I click on an email (this may be unnecessary), I press `$mod+shift+c`, thunderbird is there of course, I click on another email (sometimes need to click on several emails), `scroll` crashes. As you also observed, if I don't reload the config and then click on an email, nothing happens. Thanks!

**Comment by dawsers** [comment]
I forgot to ask, when you click on a mail, does it usually open in a new window or just a new tab? I am guessing a new window because of the crash?

**Comment by dev-forty-two** [comment]
> I forgot to ask, when you click on a mail, does it usually open in a new window or just a new tab? I am guessing a new window because of the crash?

Okay, so I use the [thunderbird conversations](https://github.com/thunderbird-conversations/thunderbird-conversations) extension. On a single click, an email shows on the right pane (3-pane view), and on double click, it opens in a new tab. That's how I have configured it.

**Comment by dawsers** [comment]
I couldn't reproduce it, but I think 145b7f9a82ebcba3c6ff48b60abb4b2aaa163b48 may fix this problem.

There could be some container changing workspaces that doesn't have a pending workspace assigned to it that is causing the crash. Let me know if that fixes the issue.

Thank you.

**Comment by dev-forty-two** [comment]
> There could be some container changing workspaces that doesn't have a pending workspace assigned to it that is causing the crash. Let me know if that fixes the issue.

Okay, so it's no longer crashing, but seeing something weird (seems related to what you said above):

I start scroll, thunderbird is autostarted, I press `$mod+Ctrl+e`, thunderbird pops up, I press `$mod+shift+c`, thunderbird is there of course, I **double click** on an email to open it in a new tab, I close the tab, **thunderbird goes back to scratchpad by itself**, even if other tabs are open. 🤭

**Comment by dawsers** [comment]
Window criteria was being executed again after reloading the configuration. It should be fixed in 3320ffa9eb4de6b6a4f3ace5dc20f6c76e7f1fa5

Thank you!

**Comment by dev-forty-two** [comment]
> Window criteria was being executed again after reloading the configuration. It should be fixed in [3320ffa](https://github.com/dawsers/scroll/commit/3320ffa9eb4de6b6a4f3ace5dc20f6c76e7f1fa5)
> 
> Thank you!

Unfortunately, with this, the crash is back and also seeing the "goes back to scratchpad by itself" behaviour. Here's the bt (I do not have the `glibc` debug build though):

```
#0  0x00007ffb6af7036b in ??? () at /usr/lib/libc.so.6
#1  0x0000556af5444142 in criteria_is_equal (left=0x556b077d5ce0, right=<optimized out>)
    at ../sway-scroll-git/sway/criteria.c:881
#2  criteria_is_equal (left=0x556b077d5ce0, right=<optimized out>)
    at ../sway-scroll-git/sway/criteria.c:872
#3  view_has_executed_criteria (view=0x556b07ce1e50, criteria=0x556b077daf90)
    at ../sway-scroll-git/sway/tree/view.c:510
        item = 0x556b077d5ce0
        i = <optimized out>
#4  view_execute_criteria (view=0x556b07ce1e50)
    at ../sway-scroll-git/sway/tree/view.c:522
        criteria = 0x556b077daf90
        res_list = <optimized out>
        i = 0
        criterias = 0x556b077b3810
#5  0x00007ffb6b2ba4d0 in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
#6  0x00007ffb6a7fcac6 in ??? () at /usr/lib/libffi.so.8
#7  0x00007ffb6a7f976b in ??? () at /usr/lib/libffi.so.8
#8  0x00007ffb6a7fc06e in ffi_call () at /usr/lib/libffi.so.8
#9  0x00007ffb6b2b8532 in ??? () at /usr/lib/libwayland-server.so.0
#10 0x00007ffb6b2bdd30 in ??? () at /usr/lib/libwayland-server.so.0
#11 0x00007ffb6b2bc182 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#12 0x00007ffb6b2be297 in wl_display_run () at /usr/lib/libwayland-server.so.0
#13 0x0000556af53e0c13 in server_run (server=<optimized out>)
    at ../sway-scroll-git/sway/server.c:616
#14 main (argc=<optimized out>, argv=<optimized out>)
    at ../sway-scroll-git/sway/main.c:376
        config_path = 0x0
        c = <optimized out>
        validate = false
        debug = false
        verbose = false
```

**Comment by dawsers** [comment]
Yes, sorry, I thought I could fix the issue you mention with thunderbird going back to scratchpad by itself with the previous commit, but there is a lot more going on.

Basically, when you reload the configuration, the executed criteria for a window become invalid and need to be re-applied again. In your case, when you close the new message after a configuration reload, it will re-apply the view criteria and that is why it is sending Thunderbird back to the scratchpad (it doesn't happen in general, only with those applications that have window criteria applied). There is no data loss, you simply need to recall Thunderbird from the scratchpad, and it won't happen again (until you reload the configuration).

This is a bug in sway too. The correct solution would involve a lot of changes that are not trivial for a very small gain, which is simply having to recall the application from the scratchpad when there is a configuration reload. It is baffling and a little bit inconvenient, but hardly any trouble. The number of configuration reloads shouldn't be very high, and reloading always can lead to (other) small trouble, because it is hard to make the state exactly the same but with all the changes correctly applied.

So I reverted the change. The bug is fixed, the only small problem is what you witnessed, but it is a long standing issue in sway too, and maybe something to fix in the future.

**Comment by dawsers** [comment]
I created #117 for the "weird" criteria behavior. I am going to commit a fix for that now.

Fixed in 2f9b3cbe57a26dd3eefca4fd001fa8305ee191ce

**Comment by dev-forty-two** [comment]
Thank you very much! Can confirm that this fixes the "weirdness". Since the original (more serious) bug does not occur anymore thanks to [145b7f9](https://github.com/dawsers/scroll/commit/145b7f9a82ebcba3c6ff48b60abb4b2aaa163b48), I am closing this.
