### ISSUE TITLE
Build error on latest commit from aur

### ISSUE THREAD

**Issue by amichaitea** [dawsers/scroll#131]
### Please fill out the following:
- **Scroll Version:**
  scroll version 1.12-dev-2ec4d783 (Nov  4 2025, branch 'master')
but I am trying to install the latest aur package with paru:
aur/sway-scroll-git 1.12.r7546.c33803e-7  [Installed: 1.12.r7900.2ec4d78-1]

- **Description:**
  - The steps you took in plain English to reproduce the problem.

Here is everything I get after running paru. Sorry for the long copypaste; I just don't want to omit something that might be useful for you.

```
  Aur (1)              Old Version           New Version           Make Only
aur/sway-scroll-git  1.12.r7900.2ec4d78-1  latest-commit         No

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: sway-scroll-git 1.12.r7546.c33803e-7 (Wed 12 Nov 2025 10:14:30 AM EST)
==> Retrieving sources...
  -> Updating sway-scroll-git git repo...
  -> Found 50-systemd-user.conf
  -> Found scroll-portals.conf
==> Validating source files with b2sums...
    sway-scroll-git ... Skipped
    50-systemd-user.conf ... Passed
    scroll-portals.conf ... Passed
==> Making package: sway-scroll-git 1.12.r7546.c33803e-7 (Wed 12 Nov 2025 10:14:33 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating sway-scroll-git git repo...
  -> Found 50-systemd-user.conf
  -> Found scroll-portals.conf
==> Validating source files with b2sums...
    sway-scroll-git ... Skipped
    50-systemd-user.conf ... Passed
    scroll-portals.conf ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of sway-scroll-git git repo...
Cloning into 'sway-scroll-git'...
done.
==> Starting prepare()...
+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_pie=true -D python.bytecompile=1 sway-scroll-git build-pkgver -D sd-bus-provider=libsystemd
The Meson build system
Version: 1.9.1
Source dir: /home/amichai/.cache/paru/clone/sway-scroll-git/src/sway-scroll-git
Build dir: /home/amichai/.cache/paru/clone/sway-scroll-git/src/build-pkgver
Build type: native build
Project name: scroll
Project version: 1.12-dev
C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
C linker for the host machine: cc ld.bfd 2.45.0
Host machine cpu family: x86_64
Host machine cpu: x86_64

Executing subproject wlroots 

wlroots| Project name: wlroots
wlroots| Project version: 0.20.0-dev
wlroots| C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
wlroots| C linker for the host machine: cc ld.bfd 2.45.0
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Found pkg-config: YES (/usr/bin/pkg-config) 2.5.1
wlroots| Run-time dependency wayland-server found: YES 1.24.0
wlroots| Run-time dependency libdrm found: YES 2.4.128
wlroots| Run-time dependency xkbcommon found: YES 1.13.0
wlroots| Run-time dependency pixman-1 found: YES 0.46.4
wlroots| Library m found: YES
wlroots| Library rt found: YES
wlroots| Run-time dependency wayland-protocols found: YES 1.45
wlroots| Build-time dependency wayland-scanner found: YES 1.24.0
wlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
wlroots| Has header "linux/dma-buf.h" : YES
wlroots| Has header "sys/eventfd.h" : YES
wlroots| Run-time dependency egl found: YES 1.5
wlroots| Fetching value of define "EGL_EGLEXT_VERSION" with dependency egl: 20211210
wlroots| Run-time dependency gbm found: YES 25.2.6-arch1.1
wlroots| Run-time dependency glesv2 found: YES 3.2
wlroots| Program glslang found: YES (/usr/bin/glslang)
wlroots| Program ./embed.sh found: YES (/home/amichai/.cache/paru/clone/sway-scroll-git/src/sway-scroll-git/subprojects/wlroots/render/gles2/shaders/./embed.sh)
wlroots| Run-time dependency vulkan found: YES 1.4.328
wlroots| Check usable header "vulkan/vulkan.h" with dependency vulkan: YES
wlroots| Program glslang found: YES (/usr/bin/glslang)
wlroots| Dependency pixman-1 found: YES 0.46.4 (cached)
wlroots| Dependency gbm found: YES 25.2.6-arch1.1 (cached)
wlroots| Checking for function "memfd_create" : YES
wlroots| Checking if define "F_ADD_SEALS" exists: YES
wlroots| Has header "linux/udmabuf.h" : YES
wlroots| Run-time dependency lcms2 found: YES 2.17
wlroots| Run-time dependency libudev found: YES 258
wlroots| Run-time dependency libseat found: YES 0.9.1
wlroots| Build-time dependency hwdata found: YES 0.401
wlroots| Run-time dependency libdisplay-info found: YES 0.3.0
wlroots| Run-time dependency libliftoff found: YES 0.5.0
wlroots| Run-time dependency libinput found: YES 1.29.2
wlroots| Run-time dependency xcb found: YES 1.17.0
wlroots| Run-time dependency xcb-dri3 found: YES 1.17.0
wlroots| Run-time dependency xcb-present found: YES 1.17.0
wlroots| Run-time dependency xcb-render found: YES 1.17.0
wlroots| Run-time dependency xcb-renderutil found: YES 0.3.10
wlroots| Run-time dependency xcb-shm found: YES 1.17.0
wlroots| Run-time dependency xcb-xfixes found: YES 1.17.0
wlroots| Run-time dependency xcb-xinput found: YES 1.17.0
wlroots| Run-time dependency wayland-client found: YES 1.24.0
wlroots| Run-time dependency xwayland found: YES 24.1.9
wlroots| Dependency xcb found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-composite found: YES 1.17.0
wlroots| Run-time dependency xcb-ewmh found: YES 0.4.2
wlroots| Run-time dependency xcb-icccm found: YES 0.4.2
wlroots| Dependency xcb-render found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-res found: YES 1.17.0
wlroots| Dependency xcb-xfixes found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-errors found: YES 1.0.1
wlroots| Configuring config.h using configuration
wlroots| Configuring version.h using configuration
wlroots| Configuring config.h using configuration
wlroots| Build targets in project: 181
wlroots| Subproject wlroots finished.

Dependency wlroots-0.20 found: YES 0.20.0-dev (overridden)
Run-time dependency json-c found: YES 0.18
Run-time dependency libpcre2-8 found: YES 10.47
Dependency wayland-server found: YES 1.24.0 (cached)
Dependency wayland-client found: YES 1.24.0 (cached)
Run-time dependency wayland-cursor found: YES 1.24.0
Dependency wayland-protocols found: YES 1.45 (cached)
Dependency xkbcommon found: YES 1.13.0 (cached)
Run-time dependency cairo found: YES 1.18.4
Run-time dependency pango found: YES 1.57.0
Run-time dependency pangocairo found: YES 1.57.0
Run-time dependency gdk-pixbuf-2.0 found: YES 2.44.4
Dependency pixman-1 found: YES 0.46.4 (cached)
Run-time dependency libevdev found: YES 1.13.5
Dependency libinput found: YES 1.29.2 (cached)
Dependency xcb found: YES 1.17.0 (cached)
Dependency libdrm found: YES 2.4.128 (cached)
Dependency libudev found: YES 258 (cached)
Library m found: YES
Library rt found: YES
Dependency xcb-icccm found: YES 0.4.2 (cached)
Run-time dependency threads found: YES
Run-time dependency lua found: YES 5.4.8
Run-time dependency libsystemd found: YES 258
Header "libinput.h" has symbol "LIBINPUT_CONFIG_ACCEL_PROFILE_CUSTOM" with dependency libinput: YES 
Header "libinput.h" has symbol "LIBINPUT_CONFIG_DRAG_LOCK_ENABLED_STICKY" with dependency libinput: YES 
Build-time dependency scdoc found: YES 1.11.4
Program /usr/bin/scdoc found: YES (/usr/bin/scdoc)
Program git found: YES (/usr/bin/git)
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES (cached)
Configuring config.h using configuration
Dependency wayland-scanner found: YES 1.24.0 (cached)
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Configuring config using configuration
Run-time dependency bash-completion found: YES 2.17.0
Run-time dependency fish found: YES 4.2.0
Build targets in project: 218

wlroots 0.20.0-dev

    drm-backend      : YES
    x11-backend      : YES
    libinput-backend : YES
    xwayland         : YES
    gles2-renderer   : YES
    vulkan-renderer  : YES
    gbm-allocator    : YES
    udmabuf-allocator: YES
    session          : YES
    color-management : YES
    xcb-errors       : YES
    egl              : YES
    libliftoff       : YES

scroll 1.12-dev

    gdk-pixbuf        : YES
    tray              : YES
    man-pages         : YES

  Subprojects
    wlroots           : YES

  User defined options
    auto_features     : enabled
    b_pie             : true
    buildtype         : plain
    libexecdir        : lib
    prefix            : /usr
    python.bytecompile: 1
    sbindir           : bin
    sd-bus-provider   : libsystemd
    wrap_mode         : nodownload

Found ninja-1.13.1 at /usr/bin/ninja
==> Starting pkgver()...                                                                  
==> Updated version: sway-scroll-git 1.12.r7909.9d7b904-1
==> Sources are ready.
sway-scroll-git-1.12.r7546.c33803e-7: parsing pkg list...
==> Making package: sway-scroll-git 1.12.r7909.9d7b904-1 (Wed 12 Nov 2025 10:14:45 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_pie=true -D python.bytecompile=1 sway-scroll-git build -D sd-bus-provider=libsystemd
The Meson build system
Version: 1.9.1
Source dir: /home/amichai/.cache/paru/clone/sway-scroll-git/src/sway-scroll-git
Build dir: /home/amichai/.cache/paru/clone/sway-scroll-git/src/build
Build type: native build
Project name: scroll
Project version: 1.12-dev
C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
C linker for the host machine: cc ld.bfd 2.45.0
Host machine cpu family: x86_64
Host machine cpu: x86_64

Executing subproject wlroots 

wlroots| Project name: wlroots
wlroots| Project version: 0.20.0-dev
wlroots| C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
wlroots| C linker for the host machine: cc ld.bfd 2.45.0
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Found pkg-config: YES (/usr/bin/pkg-config) 2.5.1
wlroots| Run-time dependency wayland-server found: YES 1.24.0
wlroots| Run-time dependency libdrm found: YES 2.4.128
wlroots| Run-time dependency xkbcommon found: YES 1.13.0
wlroots| Run-time dependency pixman-1 found: YES 0.46.4
wlroots| Library m found: YES
wlroots| Library rt found: YES
wlroots| Run-time dependency wayland-protocols found: YES 1.45
wlroots| Build-time dependency wayland-scanner found: YES 1.24.0
wlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
wlroots| Has header "linux/dma-buf.h" : YES
wlroots| Has header "sys/eventfd.h" : YES
wlroots| Run-time dependency egl found: YES 1.5
wlroots| Fetching value of define "EGL_EGLEXT_VERSION" with dependency egl: 20211210
wlroots| Run-time dependency gbm found: YES 25.2.6-arch1.1
wlroots| Run-time dependency glesv2 found: YES 3.2
wlroots| Program glslang found: YES (/usr/bin/glslang)
wlroots| Program ./embed.sh found: YES (/home/amichai/.cache/paru/clone/sway-scroll-git/src/sway-scroll-git/subprojects/wlroots/render/gles2/shaders/./embed.sh)
wlroots| Run-time dependency vulkan found: YES 1.4.328
wlroots| Check usable header "vulkan/vulkan.h" with dependency vulkan: YES
wlroots| Program glslang found: YES (/usr/bin/glslang)
wlroots| Dependency pixman-1 found: YES 0.46.4 (cached)
wlroots| Dependency gbm found: YES 25.2.6-arch1.1 (cached)
wlroots| Checking for function "memfd_create" : YES
wlroots| Checking if define "F_ADD_SEALS" exists: YES
wlroots| Has header "linux/udmabuf.h" : YES
wlroots| Run-time dependency lcms2 found: YES 2.17
wlroots| Run-time dependency libudev found: YES 258
wlroots| Run-time dependency libseat found: YES 0.9.1
wlroots| Build-time dependency hwdata found: YES 0.401
wlroots| Run-time dependency libdisplay-info found: YES 0.3.0
wlroots| Run-time dependency libliftoff found: YES 0.5.0
wlroots| Run-time dependency libinput found: YES 1.29.2
wlroots| Run-time dependency xcb found: YES 1.17.0
wlroots| Run-time dependency xcb-dri3 found: YES 1.17.0
wlroots| Run-time dependency xcb-present found: YES 1.17.0
wlroots| Run-time dependency xcb-render found: YES 1.17.0
wlroots| Run-time dependency xcb-renderutil found: YES 0.3.10
wlroots| Run-time dependency xcb-shm found: YES 1.17.0
wlroots| Run-time dependency xcb-xfixes found: YES 1.17.0
wlroots| Run-time dependency xcb-xinput found: YES 1.17.0
wlroots| Run-time dependency wayland-client found: YES 1.24.0
wlroots| Run-time dependency xwayland found: YES 24.1.9
wlroots| Dependency xcb found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-composite found: YES 1.17.0
wlroots| Run-time dependency xcb-ewmh found: YES 0.4.2
wlroots| Run-time dependency xcb-icccm found: YES 0.4.2
wlroots| Dependency xcb-render found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-res found: YES 1.17.0
wlroots| Dependency xcb-xfixes found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-errors found: YES 1.0.1
wlroots| Configuring config.h using configuration
wlroots| Configuring version.h using configuration
wlroots| Configuring config.h using configuration
wlroots| Build targets in project: 181
wlroots| Subproject wlroots finished.

Dependency wlroots-0.20 found: YES 0.20.0-dev (overridden)
Run-time dependency json-c found: YES 0.18
Run-time dependency libpcre2-8 found: YES 10.47
Dependency wayland-server found: YES 1.24.0 (cached)
Dependency wayland-client found: YES 1.24.0 (cached)
Run-time dependency wayland-cursor found: YES 1.24.0
Dependency wayland-protocols found: YES 1.45 (cached)
Dependency xkbcommon found: YES 1.13.0 (cached)
Run-time dependency cairo found: YES 1.18.4
Run-time dependency pango found: YES 1.57.0
Run-time dependency pangocairo found: YES 1.57.0
Run-time dependency gdk-pixbuf-2.0 found: YES 2.44.4
Dependency pixman-1 found: YES 0.46.4 (cached)
Run-time dependency libevdev found: YES 1.13.5
Dependency libinput found: YES 1.29.2 (cached)
Dependency xcb found: YES 1.17.0 (cached)
Dependency libdrm found: YES 2.4.128 (cached)
Dependency libudev found: YES 258 (cached)
Library m found: YES
Library rt found: YES
Dependency xcb-icccm found: YES 0.4.2 (cached)
Run-time dependency threads found: YES
Run-time dependency lua found: YES 5.4.8
Run-time dependency libsystemd found: YES 258
Header "libinput.h" has symbol "LIBINPUT_CONFIG_ACCEL_PROFILE_CUSTOM" with dependency libinput: YES 
Header "libinput.h" has symbol "LIBINPUT_CONFIG_DRAG_LOCK_ENABLED_STICKY" with dependency libinput: YES 
Build-time dependency scdoc found: YES 1.11.4
Program /usr/bin/scdoc found: YES (/usr/bin/scdoc)
Program git found: YES (/usr/bin/git)
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES (cached)
Configuring config.h using configuration
Dependency wayland-scanner found: YES 1.24.0 (cached)
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Configuring config using configuration
Run-time dependency bash-completion found: YES 2.17.0
Run-time dependency fish found: YES 4.2.0
Build targets in project: 218

wlroots 0.20.0-dev

    drm-backend      : YES
    x11-backend      : YES
    libinput-backend : YES
    xwayland         : YES
    gles2-renderer   : YES
    vulkan-renderer  : YES
    gbm-allocator    : YES
    udmabuf-allocator: YES
    session          : YES
    color-management : YES
    xcb-errors       : YES
    egl              : YES
    libliftoff       : YES

scroll 1.12-dev

    gdk-pixbuf        : YES
    tray              : YES
    man-pages         : YES

  Subprojects
    wlroots           : YES

  User defined options
    auto_features     : enabled
    b_pie             : true
    buildtype         : plain
    libexecdir        : lib
    prefix            : /usr
    python.bytecompile: 1
    sbindir           : bin
    sd-bus-provider   : libsystemd
    wrap_mode         : nodownload

Found ninja-1.13.1 at /usr/bin/ninja
INFO: autodetecting backend as ninja                                                      
INFO: calculating backend command to run: /usr/bin/ninja -C /home/amichai/.cache/paru/clone/sway-scroll-git/src/build
ninja: Entering directory `/home/amichai/.cache/paru/clone/sway-scroll-git/src/build'
[236/729] Compiling C object subprojects/wl...libwlroots-0.20.a.p/render_vulkan_object.c.o
FAILED: [code=1] subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o 
cc -Isubprojects/wlroots/libwlroots-0.20.a.p -Isubprojects/wlroots -I../sway-scroll-git/subprojects/wlroots -Isubprojects/wlroots/include -I../sway-scroll-git/subprojects/wlroots/include -Isubprojects/wlroots/protocol -Isubprojects/wlroots/render/gles2/shaders -Isubprojects/wlroots/render/vulkan/shaders -Isubprojects/wlroots/backend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c23 -D_POSIX_C_SOURCE=200809L -DWLR_USE_UNSTABLE -DWLR_PRIVATE= -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../sway-scroll-git/subprojects/wlroots/= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -MD -MQ subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o -MF subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o.d -o subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o -c ../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c
In function ‘vk_object_create’,
    inlined from ‘vulkan_object_with_owner’ at ../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c:101:33:
../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c:88:26: error: ‘size’ may be used uninitialized [-Werror=maybe-uninitialized]
   88 |         object->buffer = vulkan_create_mapped_uniform_buffer(renderer, size);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c: In function ‘vulkan_object_with_owner’:
../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c:78:22: note: ‘size’ was declared here
   78 |         VkDeviceSize size;
      |                      ^~~~
cc1: all warnings being treated as errors
[245/729] Compiling C object subprojects/wl...bwlroots-0.20.a.p/render_vulkan_renderer.c.o
FAILED: [code=1] subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o 
cc -Isubprojects/wlroots/libwlroots-0.20.a.p -Isubprojects/wlroots -I../sway-scroll-git/subprojects/wlroots -Isubprojects/wlroots/include -I../sway-scroll-git/subprojects/wlroots/include -Isubprojects/wlroots/protocol -Isubprojects/wlroots/render/gles2/shaders -Isubprojects/wlroots/render/vulkan/shaders -Isubprojects/wlroots/backend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c23 -D_POSIX_C_SOURCE=200809L -DWLR_USE_UNSTABLE -DWLR_PRIVATE= -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../sway-scroll-git/subprojects/wlroots/= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -MD -MQ subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o -MF subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o.d -o subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o -c ../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c
In function ‘init_tex_layouts’,
    inlined from ‘get_or_create_pipeline_layout’ at ../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c:2199:7:
../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c:1573:29: error: ‘pc_size’ may be used uninitialized [-Werror=maybe-uninitialized]
 1573 |         VkPushConstantRange pc_ranges[] = {
      |                             ^~~~~~~~~
../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c: In function ‘get_or_create_pipeline_layout’:
../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c:1561:18: note: ‘pc_size’ was declared here
 1561 |         uint32_t pc_size;
      |                  ^~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'sway-scroll-git-1.12.r7546.c33803e-7': 
error: packages failed to build: sway-scroll-git-1.12.r7546.c33803e-7
```

**Comment by dawsers** [comment]
It seems you are building from a previous cached copy. There are big changes in the new version you are trying to install, including there is no need for wlroots-git any more. So I think your cached copy is creating some trouble there. Try cleaning up your paru cache `paru -Sc`, or manually deleting `/home/amichai/.cache/paru/clone/sway-scroll-git` And then rebuild. It should work, because it is the one I use.

**Comment by inigoserna** [comment]
Hi,
[initial post here, so first let me thank for your work, I became a scroll converter after a couple of weeks of the announce]

I get the same error here in Fedora 43 with a fresh git clone.

Disabling `maybe-unitialiazed` flag for vulkan renderer compilation in wlroots solves the problem.
The best way I've found is adding next in first lines of meson.build:

```
add_global_arguments('-Wno-maybe-uninitialized', language : 'c')
```

I haven't observed any instability with it while using vulkan renderer.

**Comment by dawsers** [comment]
Thank you. In your case, it may happen because those warnings are produced by a switch statement that doesn't have a `default:` statement (but all the possible values are covered), and you are using a different distribution (and maybe compiler version)

But in @amichaitea's case, it is very strange, mainly because he and I are using the same distribution (and compiler), and I compile without problems.

I am also using the vulkan renderer by default.

I am going to do something about this if Fedora also has the problem, either add the option you mention or verify those are the only two switch statements without a default value and fix them.

Thank you @inigoserna for your help.

**Comment by dawsers** [comment]
OK, this should be fixed in 492f5bbd8b2a7c6a58e55dfa7f8c1e600f95a289

Please, let me know if that solves your problems.

Thank you!

**Comment by amichaitea** [comment]
Another long copypaste, sorry! I ran paru -Sc (as shown in copypaste) and am still getting an error on build. This is happening on both my laptop and desktop; this is desktop and earlier was laptop. 

```
╰─❯ paru -Sc
Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] y
removing old packages from cache...
error: could not open file /var/cache/pacman/pkg/download-sD8eGv: Error reading fd 7

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] y
removing unused sync repositories...

Clone Directory: /home/amichai/.cache/paru/clone
:: Do you want to clean all other AUR packages from cache? [Y/n]: y

Diff Directory: /home/amichai/.cache/paru/diff
:: Do you want to remove all saved diffs? [Y/n]: y
╭─ ~/.cache/paru/clone                                                                34s  16:54:48 
╰─❯ paru
:: Synchronizing package databases...
 endeavouros is up to date
 core is up to date
 extra is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for PKGBUILD upgrades...
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1)              Old Version           New Version           Make Only
aur/sway-scroll-git  1.12.r7904.f42701e-1  latest-commit         No

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: sway-scroll-git 1.12.r7546.c33803e-7 (Wed 12 Nov 2025 04:54:54 PM EST)
==> Retrieving sources...
  -> Updating sway-scroll-git git repo...
  -> Found 50-systemd-user.conf
  -> Found scroll-portals.conf
==> Validating source files with b2sums...
    sway-scroll-git ... Skipped
    50-systemd-user.conf ... Passed
    scroll-portals.conf ... Passed
==> Making package: sway-scroll-git 1.12.r7546.c33803e-7 (Wed 12 Nov 2025 04:54:55 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating sway-scroll-git git repo...
  -> Found 50-systemd-user.conf
  -> Found scroll-portals.conf
==> Validating source files with b2sums...
    sway-scroll-git ... Skipped
    50-systemd-user.conf ... Passed
    scroll-portals.conf ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of sway-scroll-git git repo...
Cloning into 'sway-scroll-git'...
done.
==> Starting prepare()...
+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_pie=true -D python.bytecompile=1 sway-scroll-git build-pkgver -D sd-bus-provider=libsystemd
The Meson build system
Version: 1.9.1
Source dir: /home/amichai/.cache/paru/clone/sway-scroll-git/src/sway-scroll-git
Build dir: /home/amichai/.cache/paru/clone/sway-scroll-git/src/build-pkgver
Build type: native build
Project name: scroll
Project version: 1.12-dev
C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
C linker for the host machine: cc ld.bfd 2.45.0
Host machine cpu family: x86_64
Host machine cpu: x86_64

Executing subproject wlroots 

wlroots| Project name: wlroots
wlroots| Project version: 0.20.0-dev
wlroots| C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
wlroots| C linker for the host machine: cc ld.bfd 2.45.0
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Found pkg-config: YES (/bin/pkg-config) 2.5.1
wlroots| Run-time dependency wayland-server found: YES 1.24.0
wlroots| Run-time dependency libdrm found: YES 2.4.128
wlroots| Run-time dependency xkbcommon found: YES 1.13.0
wlroots| Run-time dependency pixman-1 found: YES 0.46.4
wlroots| Library m found: YES
wlroots| Library rt found: YES
wlroots| Run-time dependency wayland-protocols found: YES 1.45
wlroots| Build-time dependency wayland-scanner found: YES 1.24.0
wlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
wlroots| Has header "linux/dma-buf.h" : YES
wlroots| Has header "sys/eventfd.h" : YES
wlroots| Run-time dependency egl found: YES 1.5
wlroots| Fetching value of define "EGL_EGLEXT_VERSION" with dependency egl: 20211210
wlroots| Run-time dependency gbm found: YES 25.2.7-arch1.1
wlroots| Run-time dependency glesv2 found: YES 3.2
wlroots| Program glslang found: YES (/bin/glslang)
wlroots| Program ./embed.sh found: YES (/home/amichai/.cache/paru/clone/sway-scroll-git/src/sway-scroll-git/subprojects/wlroots/render/gles2/shaders/./embed.sh)
wlroots| Run-time dependency vulkan found: YES 1.4.328
wlroots| Check usable header "vulkan/vulkan.h" with dependency vulkan: YES
wlroots| Program glslang found: YES (/bin/glslang)
wlroots| Dependency pixman-1 found: YES 0.46.4 (cached)
wlroots| Dependency gbm found: YES 25.2.7-arch1.1 (cached)
wlroots| Checking for function "memfd_create" : YES
wlroots| Checking if define "F_ADD_SEALS" exists: YES
wlroots| Has header "linux/udmabuf.h" : YES
wlroots| Run-time dependency lcms2 found: YES 2.17
wlroots| Run-time dependency libudev found: YES 258
wlroots| Run-time dependency libseat found: YES 0.9.1
wlroots| Build-time dependency hwdata found: YES 0.401
wlroots| Run-time dependency libdisplay-info found: YES 0.3.0
wlroots| Run-time dependency libliftoff found: YES 0.5.0
wlroots| Run-time dependency libinput found: YES 1.29.2
wlroots| Run-time dependency xcb found: YES 1.17.0
wlroots| Run-time dependency xcb-dri3 found: YES 1.17.0
wlroots| Run-time dependency xcb-present found: YES 1.17.0
wlroots| Run-time dependency xcb-render found: YES 1.17.0
wlroots| Run-time dependency xcb-renderutil found: YES 0.3.10
wlroots| Run-time dependency xcb-shm found: YES 1.17.0
wlroots| Run-time dependency xcb-xfixes found: YES 1.17.0
wlroots| Run-time dependency xcb-xinput found: YES 1.17.0
wlroots| Run-time dependency wayland-client found: YES 1.24.0
wlroots| Run-time dependency xwayland found: YES 24.1.9
wlroots| Dependency xcb found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-composite found: YES 1.17.0
wlroots| Run-time dependency xcb-ewmh found: YES 0.4.2
wlroots| Run-time dependency xcb-icccm found: YES 0.4.2
wlroots| Dependency xcb-render found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-res found: YES 1.17.0
wlroots| Dependency xcb-xfixes found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-errors found: YES 1.0.1
wlroots| Configuring config.h using configuration
wlroots| Configuring version.h using configuration
wlroots| Configuring config.h using configuration
wlroots| Build targets in project: 181
wlroots| Subproject wlroots finished.

Dependency wlroots-0.20 found: YES 0.20.0-dev (overridden)
Run-time dependency json-c found: YES 0.18
Run-time dependency libpcre2-8 found: YES 10.47
Dependency wayland-server found: YES 1.24.0 (cached)
Dependency wayland-client found: YES 1.24.0 (cached)
Run-time dependency wayland-cursor found: YES 1.24.0
Dependency wayland-protocols found: YES 1.45 (cached)
Dependency xkbcommon found: YES 1.13.0 (cached)
Run-time dependency cairo found: YES 1.18.4
Run-time dependency pango found: YES 1.57.0
Run-time dependency pangocairo found: YES 1.57.0
Run-time dependency gdk-pixbuf-2.0 found: YES 2.44.4
Dependency pixman-1 found: YES 0.46.4 (cached)
Run-time dependency libevdev found: YES 1.13.5
Dependency libinput found: YES 1.29.2 (cached)
Dependency xcb found: YES 1.17.0 (cached)
Dependency libdrm found: YES 2.4.128 (cached)
Dependency libudev found: YES 258 (cached)
Library m found: YES
Library rt found: YES
Dependency xcb-icccm found: YES 0.4.2 (cached)
Run-time dependency threads found: YES
Run-time dependency lua found: YES 5.4.8
Run-time dependency libsystemd found: YES 258
Header "libinput.h" has symbol "LIBINPUT_CONFIG_ACCEL_PROFILE_CUSTOM" with dependency libinput: YES 
Header "libinput.h" has symbol "LIBINPUT_CONFIG_DRAG_LOCK_ENABLED_STICKY" with dependency libinput: YES 
Build-time dependency scdoc found: YES 1.11.4
Program /usr/bin/scdoc found: YES (/usr/bin/scdoc)
Program git found: YES (/bin/git)
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES (cached)
Configuring config.h using configuration
Dependency wayland-scanner found: YES 1.24.0 (cached)
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Configuring config using configuration
Run-time dependency bash-completion found: YES 2.17.0
Run-time dependency fish found: YES 4.2.0
Build targets in project: 218

wlroots 0.20.0-dev

    drm-backend      : YES
    x11-backend      : YES
    libinput-backend : YES
    xwayland         : YES
    gles2-renderer   : YES
    vulkan-renderer  : YES
    gbm-allocator    : YES
    udmabuf-allocator: YES
    session          : YES
    color-management : YES
    xcb-errors       : YES
    egl              : YES
    libliftoff       : YES

scroll 1.12-dev

    gdk-pixbuf        : YES
    tray              : YES
    man-pages         : YES

  Subprojects
    wlroots           : YES

  User defined options
    auto_features     : enabled
    b_pie             : true
    buildtype         : plain
    libexecdir        : lib
    prefix            : /usr
    python.bytecompile: 1
    sbindir           : bin
    sd-bus-provider   : libsystemd
    wrap_mode         : nodownload

Found ninja-1.13.1 at /bin/ninja
==> Starting pkgver()...                                                                               
==> Updated version: sway-scroll-git 1.12.r7912.d9af473-1
==> Sources are ready.
sway-scroll-git-1.12.r7546.c33803e-7: parsing pkg list...
==> Making package: sway-scroll-git 1.12.r7912.d9af473-1 (Wed 12 Nov 2025 04:54:58 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_pie=true -D python.bytecompile=1 sway-scroll-git build -D sd-bus-provider=libsystemd
The Meson build system
Version: 1.9.1
Source dir: /home/amichai/.cache/paru/clone/sway-scroll-git/src/sway-scroll-git
Build dir: /home/amichai/.cache/paru/clone/sway-scroll-git/src/build
Build type: native build
Project name: scroll
Project version: 1.12-dev
C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
C linker for the host machine: cc ld.bfd 2.45.0
Host machine cpu family: x86_64
Host machine cpu: x86_64

Executing subproject wlroots 

wlroots| Project name: wlroots
wlroots| Project version: 0.20.0-dev
wlroots| C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
wlroots| C linker for the host machine: cc ld.bfd 2.45.0
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Found pkg-config: YES (/bin/pkg-config) 2.5.1
wlroots| Run-time dependency wayland-server found: YES 1.24.0
wlroots| Run-time dependency libdrm found: YES 2.4.128
wlroots| Run-time dependency xkbcommon found: YES 1.13.0
wlroots| Run-time dependency pixman-1 found: YES 0.46.4
wlroots| Library m found: YES
wlroots| Library rt found: YES
wlroots| Run-time dependency wayland-protocols found: YES 1.45
wlroots| Build-time dependency wayland-scanner found: YES 1.24.0
wlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
wlroots| Has header "linux/dma-buf.h" : YES
wlroots| Has header "sys/eventfd.h" : YES
wlroots| Run-time dependency egl found: YES 1.5
wlroots| Fetching value of define "EGL_EGLEXT_VERSION" with dependency egl: 20211210
wlroots| Run-time dependency gbm found: YES 25.2.7-arch1.1
wlroots| Run-time dependency glesv2 found: YES 3.2
wlroots| Program glslang found: YES (/bin/glslang)
wlroots| Program ./embed.sh found: YES (/home/amichai/.cache/paru/clone/sway-scroll-git/src/sway-scroll-git/subprojects/wlroots/render/gles2/shaders/./embed.sh)
wlroots| Run-time dependency vulkan found: YES 1.4.328
wlroots| Check usable header "vulkan/vulkan.h" with dependency vulkan: YES
wlroots| Program glslang found: YES (/bin/glslang)
wlroots| Dependency pixman-1 found: YES 0.46.4 (cached)
wlroots| Dependency gbm found: YES 25.2.7-arch1.1 (cached)
wlroots| Checking for function "memfd_create" : YES
wlroots| Checking if define "F_ADD_SEALS" exists: YES
wlroots| Has header "linux/udmabuf.h" : YES
wlroots| Run-time dependency lcms2 found: YES 2.17
wlroots| Run-time dependency libudev found: YES 258
wlroots| Run-time dependency libseat found: YES 0.9.1
wlroots| Build-time dependency hwdata found: YES 0.401
wlroots| Run-time dependency libdisplay-info found: YES 0.3.0
wlroots| Run-time dependency libliftoff found: YES 0.5.0
wlroots| Run-time dependency libinput found: YES 1.29.2
wlroots| Run-time dependency xcb found: YES 1.17.0
wlroots| Run-time dependency xcb-dri3 found: YES 1.17.0
wlroots| Run-time dependency xcb-present found: YES 1.17.0
wlroots| Run-time dependency xcb-render found: YES 1.17.0
wlroots| Run-time dependency xcb-renderutil found: YES 0.3.10
wlroots| Run-time dependency xcb-shm found: YES 1.17.0
wlroots| Run-time dependency xcb-xfixes found: YES 1.17.0
wlroots| Run-time dependency xcb-xinput found: YES 1.17.0
wlroots| Run-time dependency wayland-client found: YES 1.24.0
wlroots| Run-time dependency xwayland found: YES 24.1.9
wlroots| Dependency xcb found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-composite found: YES 1.17.0
wlroots| Run-time dependency xcb-ewmh found: YES 0.4.2
wlroots| Run-time dependency xcb-icccm found: YES 0.4.2
wlroots| Dependency xcb-render found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-res found: YES 1.17.0
wlroots| Dependency xcb-xfixes found: YES 1.17.0 (cached)
wlroots| Run-time dependency xcb-errors found: YES 1.0.1
wlroots| Configuring config.h using configuration
wlroots| Configuring version.h using configuration
wlroots| Configuring config.h using configuration
wlroots| Build targets in project: 181
wlroots| Subproject wlroots finished.

Dependency wlroots-0.20 found: YES 0.20.0-dev (overridden)
Run-time dependency json-c found: YES 0.18
Run-time dependency libpcre2-8 found: YES 10.47
Dependency wayland-server found: YES 1.24.0 (cached)
Dependency wayland-client found: YES 1.24.0 (cached)
Run-time dependency wayland-cursor found: YES 1.24.0
Dependency wayland-protocols found: YES 1.45 (cached)
Dependency xkbcommon found: YES 1.13.0 (cached)
Run-time dependency cairo found: YES 1.18.4
Run-time dependency pango found: YES 1.57.0
Run-time dependency pangocairo found: YES 1.57.0
Run-time dependency gdk-pixbuf-2.0 found: YES 2.44.4
Dependency pixman-1 found: YES 0.46.4 (cached)
Run-time dependency libevdev found: YES 1.13.5
Dependency libinput found: YES 1.29.2 (cached)
Dependency xcb found: YES 1.17.0 (cached)
Dependency libdrm found: YES 2.4.128 (cached)
Dependency libudev found: YES 258 (cached)
Library m found: YES
Library rt found: YES
Dependency xcb-icccm found: YES 0.4.2 (cached)
Run-time dependency threads found: YES
Run-time dependency lua found: YES 5.4.8
Run-time dependency libsystemd found: YES 258
Header "libinput.h" has symbol "LIBINPUT_CONFIG_ACCEL_PROFILE_CUSTOM" with dependency libinput: YES 
Header "libinput.h" has symbol "LIBINPUT_CONFIG_DRAG_LOCK_ENABLED_STICKY" with dependency libinput: YES 
Build-time dependency scdoc found: YES 1.11.4
Program /usr/bin/scdoc found: YES (/usr/bin/scdoc)
Program git found: YES (/bin/git)
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES (cached)
Configuring config.h using configuration
Dependency wayland-scanner found: YES 1.24.0 (cached)
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Configuring config using configuration
Run-time dependency bash-completion found: YES 2.17.0
Run-time dependency fish found: YES 4.2.0
Build targets in project: 218

wlroots 0.20.0-dev

    drm-backend      : YES
    x11-backend      : YES
    libinput-backend : YES
    xwayland         : YES
    gles2-renderer   : YES
    vulkan-renderer  : YES
    gbm-allocator    : YES
    udmabuf-allocator: YES
    session          : YES
    color-management : YES
    xcb-errors       : YES
    egl              : YES
    libliftoff       : YES

scroll 1.12-dev

    gdk-pixbuf        : YES
    tray              : YES
    man-pages         : YES

  Subprojects
    wlroots           : YES

  User defined options
    auto_features     : enabled
    b_pie             : true
    buildtype         : plain
    libexecdir        : lib
    prefix            : /usr
    python.bytecompile: 1
    sbindir           : bin
    sd-bus-provider   : libsystemd
    wrap_mode         : nodownload

Found ninja-1.13.1 at /bin/ninja
INFO: autodetecting backend as ninja                                                                   
INFO: calculating backend command to run: /bin/ninja -C /home/amichai/.cache/paru/clone/sway-scroll-git/src/build
ninja: Entering directory `/home/amichai/.cache/paru/clone/sway-scroll-git/src/build'
[236/729] Compiling C object subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o
FAILED: [code=1] subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o 
cc -Isubprojects/wlroots/libwlroots-0.20.a.p -Isubprojects/wlroots -I../sway-scroll-git/subprojects/wlroots -Isubprojects/wlroots/include -I../sway-scroll-git/subprojects/wlroots/include -Isubprojects/wlroots/protocol -Isubprojects/wlroots/render/gles2/shaders -Isubprojects/wlroots/render/vulkan/shaders -Isubprojects/wlroots/backend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c23 -D_POSIX_C_SOURCE=200809L -DWLR_USE_UNSTABLE -DWLR_PRIVATE= -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../sway-scroll-git/subprojects/wlroots/= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -MD -MQ subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o -MF subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o.d -o subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_object.c.o -c ../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c
In function ‘vk_object_create’,
    inlined from ‘vulkan_object_with_owner’ at ../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c:101:33:
../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c:88:26: error: ‘size’ may be used uninitialized [-Werror=maybe-uninitialized]
   88 |         object->buffer = vulkan_create_mapped_uniform_buffer(renderer, size);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c: In function ‘vulkan_object_with_owner’:
../sway-scroll-git/subprojects/wlroots/render/vulkan/object.c:78:22: note: ‘size’ was declared here
   78 |         VkDeviceSize size;
      |                      ^~~~
cc1: all warnings being treated as errors
[245/729] Compiling C object subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o
FAILED: [code=1] subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o 
cc -Isubprojects/wlroots/libwlroots-0.20.a.p -Isubprojects/wlroots -I../sway-scroll-git/subprojects/wlroots -Isubprojects/wlroots/include -I../sway-scroll-git/subprojects/wlroots/include -Isubprojects/wlroots/protocol -Isubprojects/wlroots/render/gles2/shaders -Isubprojects/wlroots/render/vulkan/shaders -Isubprojects/wlroots/backend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c23 -D_POSIX_C_SOURCE=200809L -DWLR_USE_UNSTABLE -DWLR_PRIVATE= -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../sway-scroll-git/subprojects/wlroots/= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -MD -MQ subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o -MF subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o.d -o subprojects/wlroots/libwlroots-0.20.a.p/render_vulkan_renderer.c.o -c ../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c
In function ‘init_tex_layouts’,
    inlined from ‘get_or_create_pipeline_layout’ at ../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c:2199:7:
../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c:1573:29: error: ‘pc_size’ may be used uninitialized [-Werror=maybe-uninitialized]
 1573 |         VkPushConstantRange pc_ranges[] = {
      |                             ^~~~~~~~~
../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c: In function ‘get_or_create_pipeline_layout’:
../sway-scroll-git/subprojects/wlroots/render/vulkan/renderer.c:1561:18: note: ‘pc_size’ was declared here
 1561 |         uint32_t pc_size;
      |                  ^~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'sway-scroll-git-1.12.r7546.c33803e-7': 
error: packages failed to build: sway-scroll-git-1.12.r7546.c33803e-7
```

**Comment by inigoserna** [comment]
> OK, this should be fixed in [492f5bb](https://github.com/dawsers/scroll/commit/492f5bbd8b2a7c6a58e55dfa7f8c1e600f95a289)
> 
> Please, let me know if that solves your problems.
> 
> Thank you!

It compiles without errors here now. Thanks.

**Comment by amichaitea** [comment]
Works perfectly for me now as well, thank you both so much!

**Comment by dawsers** [comment]
@amichaitea sorry I misguided you initially, but it was quite baffling that you and I are using the same distribution and the same AUR helper (`paru`) and I wasn't having the problem. Could you post your `paru.conf`, please?

``` bash
cat /etc/paru.conf
cat ~/.config/paru/paru.conf
```

I think there must be something wrong with my configuration because yours creates release builds by default and mine is doing something different. I would like to fix it so this doesn't happen again in the future. Thank you.

**Comment by amichaitea** [comment]
Of course, glad to have the chance to help. I never edited it from what it was installed with:

(editing to add: don't feel bad about "misleading" me; I have indeed had issues updating packages before because of paru holding onto a cache that caused the problem! so it was a very good first step to try in troubleshooting. I regularly read issue reports people post here and you are always a great model of how to solve problems and explain things.)

```
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas
```

**Comment by dawsers** [comment]
Thank you!
